config/routes.rb
Rails.application.routes.draw do
  devise_for :candidates

  root 'welcome#index'

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

# == Schema Information
#
# Table name: candidates
#
#  id                     :integer          not null, primary key
#  firstname              :string(255)
#  lastname               :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#

app/models/skill.rb
class Skill < ActiveRecord::Base
end

# == Schema Information
#
# Table name: skills
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :firstname
    devise_parameter_sanitizer.for(:sign_up) << :lastname
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  def index
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ManpowerPhilippines
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      %topnav
        .pull-right
          - if candidate_signed_in?
            = link_to "Sign out", destroy_candidate_session_path, method: :delete
          - else
            = link_to "Sign in", root_path
      %p.notice= notice
      %p.alert= alert
      = yield

app/views/welcome/index.html.haml
%h1 Manpower Search

.row.jumbotron.hero
  .col-lg-6.text-right
    .section.hero
      %p Kailangan mo ba ng tao sa iyong construction business?
      .row
        = text_field_tag '', '', placeholder: 'Welder / Foreman', class: 'form-control'
      .row
        = link_to "Maghanap!", '#', class: "btn btn-lg btn-warning"

  .col-lg-6.text-left
    .section.hero
      %p Naghahanap ka ba ng trabahong pisikal?
      %p= link_to "Sali na", new_candidate_registration_path, class: "btn btn-lg btn-success"